version: "3.9"
services:
  front-app:
    image: inventory-front
    container_name: front-app
    restart: always
    ports:
      - 4200:4200
    environment:
      HOST_3000: "172.25.83.113:30000"
      HOST_3001: "172.25.83.113:30001"
      HOST_3002: "172.25.83.113:30002"
      HOST_81: "172.25.83.113:30081"
    volumes:
      - front-app:/usr/share/nginx/html

volumes:
  front-app:
    name: front-app
    driver: local
